# -*- coding: utf-8 -*-


from PyQt4 import QtCore, QtGui
import sqlite3
import os

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def add(self):
        save_path='database/'
        complete = os.path.join(save_path,"user.sqlite")
        db = sqlite3.connect(complete)
        cur= db.cursor()
        name = unicode(self.name.text())
        surname = unicode(self.surname.text())
        username = unicode(self.username.text())
        password = unicode(self.password.text())
        role = unicode(self.role.currentText())
        clearance = unicode(self.clearance.currentText())
        cur.execute('Insert into users (Name,Surname,Username,Password,Role,Clearance) values(?,?,?,?,?,?)',(name,surname,username,password,role,clearance))
        db.commit()
        print("done")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(310, 374)
        MainWindow.setMaximumSize(QtCore.QSize(310, 374))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../tests/access-control-icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 213, 201, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.role = QtGui.QComboBox(self.layoutWidget)
        self.role.setObjectName(_fromUtf8("role"))
        self.role.addItem(_fromUtf8(""))
        self.role.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.role)
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 100, 201, 31))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.surname = QtGui.QLineEdit(self.layoutWidget_2)
        self.surname.setObjectName(_fromUtf8("surname"))
        self.horizontalLayout_2.addWidget(self.surname)
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 63, 201, 31))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.name = QtGui.QLineEdit(self.layoutWidget_3)
        self.name.setObjectName(_fromUtf8("name"))
        self.horizontalLayout.addWidget(self.name)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 293, 87, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton.clicked.connect(self.add)

        self.layoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 253, 201, 31))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.clearance = QtGui.QComboBox(self.layoutWidget_4)
        self.clearance.setObjectName(_fromUtf8("clearance"))
        self.clearance.addItem(_fromUtf8(""))
        self.clearance.addItem(_fromUtf8(""))
        self.clearance.addItem(_fromUtf8(""))
        self.clearance.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.clearance)
        self.layoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 143, 200, 28))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.username = QtGui.QLineEdit(self.layoutWidget_5)
        self.username.setObjectName(_fromUtf8("username"))
        self.horizontalLayout_3.addWidget(self.username)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 23, 58, 14))
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 180, 201, 31))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.password = QtGui.QLineEdit(self.layoutWidget_6)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_4.addWidget(self.password)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 310, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Users", None))
        self.label_6.setText(_translate("MainWindow", "Role", None))
        self.role.setItemText(0, _translate("MainWindow", "User", None))
        self.role.setItemText(1, _translate("MainWindow", "Admin", None))
        self.label_3.setText(_translate("MainWindow", "Surname", None))
        self.label_2.setText(_translate("MainWindow", "Name", None))
        self.pushButton.setText(_translate("MainWindow", "Add", None))
        self.label_7.setText(_translate("MainWindow", "Clearance", None))
        self.clearance.setItemText(0, _translate("MainWindow", "UNCLASSIFIED", None))
        self.clearance.setItemText(1, _translate("MainWindow", "CONFIDENTIAL", None))
        self.clearance.setItemText(2, _translate("MainWindow", "SECRET", None))
        self.clearance.setItemText(3, _translate("MainWindow", "TOP SECRET", None))
        self.label_4.setText(_translate("MainWindow", "Username", None))
        self.label_5.setText(_translate("MainWindow", "Password", None))

